### PR TITLE
Spanish Translation

### PR DESCRIPTION
**Pull request by xa31er**
### Progress: 
- Home page translated.
- Credits page translated.

### CODE REVIEW

**Comment by Naviary2** [comment]
Hey! Just checking in to see if you were still working on this?

**Comment by Naviary2** [comment]
RIP Spanish translation :skull:

**Comment by xa31er** [comment]
Sorry, but I had to go on vacation w/ family and couldn't work on it. 

More work coming up! 😅

**Comment by xa31er** [comment]
Sorry for the slow progress, things should speed up in September as I'm going to have more time at home.

**Comment by Naviary2** [comment]
There hasn't been any changes on this in a long time. I will close this. Feel free in the future when it is finished to open another PR!

**Pull request closed without merging**
