### PR TITLE
fix header and redesign website UI

### PR DESCRIPTION
**Pull request by pihedron**
# UI Redesign

## Changes

You have to admit this looks clean.
- changed header to look better and be more responsive on mobile devices
- used glassmorphism for styling content panels
- created a `header.ejs` component for reusability
- added catchy splash text *Beyond 64 Squares*

> [!NOTE]
> The old UI from the `play` page was preserved as people wished.

## Translation

I changed the TOML a bit. French translations are still required for the new edits.

### CODE REVIEW

**Comment by pihedron** [comment]
# Bug Fixes

## Design

- fixed font not loading
- changed logo to the discord one

## Functionality

- fixed `memberHeader.js` not updating the header
- changed header height in `camera.js` to stop the dragging of the board

**Comment by pihedron** [comment]
@Naviary2 I think this is ready to be merged now.

**Comment by tsevasa** [comment]
It's nice to see that some of the bugs in your PR are fixed now. I'd like to see this succeed! I just tested your PR again, please see my feedback on discord [here](https://discord.com/channels/1114425729569017918/1115358966642393190/1267965434439929918) and [here](https://discord.com/channels/1114425729569017918/1115358966642393190/1267966617455689809).

**Comment by Naviary2** [comment]
Let me know if/when you return to this! I still would look forward to some of these changes.

**Comment by xa31er** [comment]
Are you still working on this?

**Pull request closed without merging**
