### PR TITLE
Account deletion

### PR DESCRIPTION
**Pull request by jermOSS**
Fixes https://github.com/Infinite-Chess/infinitechess.org/issues/4

### CODE REVIEW

**Comment by Naviary2** [comment]
This is awesome!!!

I think the button should be red to indicate it's a dangerous action. For example, here's one of github's dangerous buttons.

Screen Shot 2024-07-10 at 10 52 40 AM

And I think it should be at the bottom of the page, centered.

Screen Shot 2024-07-10 at 10 53 45 AM

And, more of a preference.. What if whenever a user deletes their account we log that info, to the console, and to a "deletedAccounts.txt" log?

**Comment by Naviary2** [comment]
```js
logEvents(`User ${usernameLowercase} deleted their account.`, "deletedAccounts.txt", { print: true})
```

**Comment by Naviary2** [comment]
Also, be sure to delete their role information. Inside controllers/roles.js, use `removeAllRoles()`!

**Comment by jermOSS** [comment]
@Naviary2  What about now?

**Comment by Naviary2** [comment]
What are some other opinions? I think this is completely ready now.

Screen Shot 2024-07-10 at 6 01 20 PM

Screen Shot 2024-07-10 at 6 01 46 PM

**Pull request closed without merging**
