### PR TITLE
Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by this-is-not-available**
From 6 vulnerabilities (3 high, 3 moderate severity) to 0
Also make package name correct (no uppercase and no spaces)

### CODE REVIEW

**Review by Heinrich-XIAO — COMMENTED** [review]
The name was changed. Is that intentional?

**Comment by this-is-not-available** [comment]
Probably. It makes sense though

**Comment by Heinrich-XIAO** [comment]
Also, is it still 1.0.0?

**Comment by Heinrich-XIAO** [comment]
Yeah.

**Comment by this-is-not-available** [comment]
Done

**Comment by Naviary2** [comment]
Thanks! I'll merge this.

It would be nicer if there was just one location we could keep the server version, instead of 4.. these 2 I probably won't always update

**Pull request merged**
