### PR TITLE
Warning when leaving active game

### PR DESCRIPTION
**Pull request by jermOSS**
Displays warning when trying to leave active game.

### CODE REVIEW

**Comment by Naviary2** [comment]
These are the changes that need to be made before I can merge:

* Merge the 'beforeunload' event listener with the one already declared in main.js
* Only add the popup in online games (not local or engine).
* Use gamefileutility.isGameOver() instead of directly reading the gameConclusion

**Comment by Naviary2** [comment]
The current `beforeunload` event listener can be changed to an `unload` event, then you can add a separate `beforeunload` event listener for asking the user if they want to leave.

**Comment by jermOSS** [comment]
Sadly `unload` event is deprecated.

**Comment by Naviary3** [comment]
> Sadly `unload` event is deprecated.

Ah, gotcha. Here's what I'd do then. I'd experiment with removing the line that closes the socket, and see if the socket remains connected even with the popup visible. If it stays connected then great! We can adapt without the line, the socket closure message will just be different.

**Comment by Naviary2** [comment]
Closing from inactivity. If you revisit this in the future, feel free to open another PR!

**Pull request closed without merging**
