### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by Heinrich-XIAO**

### CODE REVIEW

**Comment by tsevasa** [comment]
Note that [en-US.toml](https://github.com/Infinite-Chess/infinitechess.org/blob/main/translation/en-US.toml) just got updated to version number 5. Please see [changes.json](https://github.com/Infinite-Chess/infinitechess.org/blob/main/translation/changes.json) for the changelist, it is quite extensive. I recommend updating your current translation as soon as possible to reflect these changes. I am very sorry for the inconvience, we needed to still add some missing localizations to the website but no more such changes are foreseen for now.

**Comment by Naviary2** [comment]
Still looking forward to this!

**Comment by Heinrich-XIAO** [comment]
Translation is finally done.

**Comment by Naviary2** [comment]
> Translation is finally done.

This is looking really good!! Thanks! Are you able to translate the Terms of Service section as well? I know it was a little confusing as it said it that that translation was disabled, but that is an outdated comment, I will delete it!

**Comment by Naviary2** [comment]
I drafted a ChatGPT translation for the Terms of Service!

Screenshot 2024-08-16 at 00-45-41 Terms of Service

**Comment by Heinrich-XIAO** [comment]
I don't think there's any english left except for the variable names and the comments.

**Comment by Naviary2** [comment]
> I don't think there's any english left except for the variable names and the comments.
Variable names and comments shouldn't be translated anyway, those are constant across all languages.

Chinese is finished then :tada: :tada: !! I will merge this!

**Pull request merged**
