### PR TITLE
Dragging Pieces + Selection menu

### PR DESCRIPTION
**Pull request by BF5258**
Adds selection menu with toggle switches to disable dragging pieces and premoves.
Relates to #22 and #328
Don't merge until after #350

## To do
How do you want the menu to look?

### Possible ideas
- [x] slider animation
- [ ] sound effect when switch flicked

### CODE REVIEW

**Comment by BF5258** [comment]
This is want the menu looks like currently:
image
Any suggestions?

**Comment by Naviary2** [comment]
Very nice!

An animation would be nice, as most other websites have that.
Also, perhaps add a border? To make the edge stand out more? They feel kinda sharp.
Then I'd shrink the buttons a bit.

Is there a color difference right now between the on and off states? I think it would be cool if the on-state color matched your color theme! For inspiration:

Screenshot 2024-12-18 at 12 33 04 AM

**Comment by BF5258** [comment]
Some themes make the switch hard to see but a border should fix it.

https://github.com/user-attachments/assets/a7880a9c-db11-482c-b58b-c89894f8413e

**Comment by Naviary2** [comment]
That looks really good!

**Comment by BF5258** [comment]
There is a thin line of white pixels between the colored area and the border. Is it due to rounding error? How can I fix it?

image

**Comment by Naviary2** [comment]
It just looks like its an issue with using outline. Could we get it work work with a border instead?

**Comment by Naviary2** [comment]
Screenshot 2024-12-20 at 2 45 18 AM
Screenshot 2024-12-20 at 2 45 28 AM
Perhaps a white button would look better for our light theme. Similar to these. The off-state background color could be a tad darker tho imo

**Comment by Naviary2** [comment]
Reviewed! With my notes in this post https://discord.com/channels/1114425729569017918/1115358966642393190/1320665870359593051

**Pull request merged**
