### PR TITLE
Add more reserved usernames

### PR DESCRIPTION
**Pull request by this-is-not-available**
Add more reserved usernames to prevent impersonation of big companies/games/actors.

### CODE REVIEW

**Comment by this-is-not-available** [comment]
Whoops..

**Comment by this-is-not-available** [comment]
Ok now this only has the reserved usernames (and an additional 4 commits)

**Comment by this-is-not-available** [comment]
Great, now I lost my progress on the frontend of the draw offering, because I didn't merge it with my fork's main
Silly old me

**Comment by Naviary2** [comment]
Of this list of new reserved usernames, the following already have accounts associated with them:

admin, amazon, google, tesla, epic, epicgames, usa, america

**Pull request merged**
