### PR TITLE
Greater password security

### PR DESCRIPTION
**Pull request by Heinrich-XIAO**

### CODE REVIEW

**Comment by Heinrich-XIAO** [comment]
This fixes #16

**Comment by life-enjoyer** [comment]
It's great but the regex in [this post](https://stackoverflow.com/a/201378) is more complete I think. I've already made a PR with it: #18

**Comment by Naviary2** [comment]
Screen Shot 2024-07-09 at 10 21 28 PM
I get this when a try to create a new account.

Btw the regex has been updated.

**Comment by tsevasa** [comment]
Why is there a maximum password length of 30 characters? I would be in favor of increasing it to something larger, like 128, if there is no reason against it.

**Comment by tsevasa** [comment]
I would also argue in favor of dropping the requirements for special characters, numbers, capitalized letters, etc. I feel like this might annoy people and infinite chess really doesn't need to be so restrictive, in my opinion.

**Comment by Naviary2** [comment]
True, it does kind of seem excessive to have (such) strong password requirements, at least while this is still small, I can see it annoying people.

**Comment by 5jiji** [comment]
> Why is there a maximum password length of 30 characters? I would be in favor of increasing it to something larger, like 128, if there is no reason against it.

I'm wondering, why limit the length of the password at all?
Being that the password is hashed, why would we even enforce a length

**Comment by tsevasa** [comment]
Ok, fair enough, you are right. Thinking about it again, I agree that there should be no maximum password length, it really makes no sense. Also, [this argument](https://stackoverflow.com/a/99724/19730773) makes sense:
```A maximum length specified on a password field should be read as a SECURITY WARNING. Any sensible, security conscious user must assume the worst and expect that this site is storing your password literally (i.e. not hashed).```

I would suggest to just enforce a minimum a password length of 8 characters and leave it at that.

**Pull request closed without merging**
