### PR TITLE
Update translations to version 20

### PR DESCRIPTION
**Pull request by xa31er**
- Updated Spanish and English to version 20.
- Fixed Issue #281 
- Fixed Issue #280

### CODE REVIEW

**Comment by Naviary2** [comment]
Thank you :)

**Comment by Naviary2** [comment]
closes #281

**Comment by Naviary2** [comment]
closes #280

**Comment by xa31er** [comment]
Did they auto-close?

**Comment by Naviary2** [comment]
I closed them manually, I think we have to say that before it is merged.

**Pull request merged**
