### PR TITLE
Create 2024-11-09

### PR DESCRIPTION
**Pull request by cycy98**
made last update

### CODE REVIEW

**Comment by Naviary2** [comment]
Have you taken a look at Life Enjoyer's suggestions in the translations channel?

**Comment by cycy98** [comment]
yea im editing my mistakes

**Review by Heinrich-XIAO — APPROVED** [review]

**Comment by Naviary2** [comment]
@cycy98 Is that everything? Is this ready to be merged?

**Review by Heinrich-XIAO — CHANGES_REQUESTED** [review]
`de Infinite Chess` to `d'Infinite Chess` on line 1
`Pour plus de mises à jours` to `Pour plus de mises à jour` on line 4
`invitaion` to `invitation` on line 13

**Comment by cycy98** [comment]
> `de Infinite Chess` to `d'Infinite Chess` on line 1 `Pour plus de mises à jours` to `Pour plus de mises à jour` on line 4 `invitaion` to `invitation` on line 13

Thanks 👍

**Comment by cycy98** [comment]
> @cycy98 Is that everything? Is this ready to be merged?

Yes, do it.

**Pull request merged**
